"""
NSO Network Protocol Command Constants
"""

# Client Outgoing Commands
CMD_KEY_REQUEST = -27
CMD_LOGIN = -127
CMD_SELECT_CHAR = -126
CMD_SUB_COMMAND = -30
CMD_NOT_LOGIN = -29
CMD_NOT_MAP = -28

CMD_CHAR_MOVE = 1
CMD_USE_ITEM = 11
CMD_BUY_ITEM = 13
CMD_SALE_ITEM = 14
CMD_ITEM_BOX_TO_BAG = 16
CMD_ITEM_BAG_TO_BOX = 17
CMD_REQUEST_CHANGE_MAP = -17
CMD_REQUEST_CHANGE_ZONE = 28
CMD_MENU = 29
CMD_OPEN_MENU = 40
CMD_SELECT_SKILL = 41
CMD_PICK_ITEM = -14
CMD_ATTACK_MOB_FAST = 119
CMD_RANKED = 121

# Sub Commands for CMD_NOT_LOGIN (-29)
SUB_CMD_SET_CLIENT = -125
SUB_CMD_LOGIN = -127

# Sub Commands for CMD_NOT_MAP (-28)
SUB_CMD_SELECT_CARD = -72
SUB_CMD_BUY_ITEM1 = 122
SUB_CMD_REQUEST_ITEM = 4
SUB_CMD_SELECT_CHAR_PLAY = -126

# Server Incoming Commands
SERVER_CMD_SERVER_MESSAGE = -26
SERVER_CMD_MAP_LOAD = -18
SERVER_CMD_MAP_ITEM_REMOVE = -15
SERVER_CMD_MAP_ITEM_ADD = -14
SERVER_CMD_MAP_ITEM_UPDATE = -13
SERVER_CMD_SUB_COMMAND = -30
SERVER_CMD_NOT_MAP = -28
SERVER_CMD_DIALOG = -25
SERVER_CMD_TASK_ADD = 96
SERVER_CMD_TASK_UPDATE = 97
SERVER_CMD_TASK_REMOVE = 98

SERVER_CMD_OPEN_MENU = 40
SERVER_CMD_CHAT_NPC = 47
